package com.fountainpdl.bible.utils;

import java.util.HashMap;
import java.util.Map;

public class VerseCounts {

    private static final Map<String, Integer> COUNTS = new HashMap<>();
    static {
        COUNTS.put("Genesis:1", 31);
        COUNTS.put("Genesis:2", 25);
        COUNTS.put("Genesis:3", 24);
        COUNTS.put("Genesis:4", 26);
        COUNTS.put("Genesis:5", 32);
        COUNTS.put("Genesis:6", 22);
        COUNTS.put("Genesis:7", 24);
        COUNTS.put("Genesis:8", 22);
        COUNTS.put("Genesis:9", 29);
        COUNTS.put("Genesis:10", 32);
        COUNTS.put("Genesis:11", 32);
        COUNTS.put("Genesis:12", 20);
        COUNTS.put("Genesis:13", 18);
        COUNTS.put("Genesis:14", 24);
        COUNTS.put("Genesis:15", 21);
        COUNTS.put("Genesis:16", 16);
        COUNTS.put("Genesis:17", 27);
        COUNTS.put("Genesis:18", 33);
        COUNTS.put("Genesis:19", 38);
        COUNTS.put("Genesis:20", 18);
        COUNTS.put("Genesis:21", 34);
        COUNTS.put("Genesis:22", 24);
        COUNTS.put("Genesis:23", 20);
        COUNTS.put("Genesis:24", 67);
        COUNTS.put("Genesis:25", 34);
        COUNTS.put("Genesis:26", 35);
        COUNTS.put("Genesis:27", 46);
        COUNTS.put("Genesis:28", 22);
        COUNTS.put("Genesis:29", 35);
        COUNTS.put("Genesis:30", 43);
        COUNTS.put("Genesis:31", 55);
        COUNTS.put("Genesis:32", 32);
        COUNTS.put("Genesis:33", 20);
        COUNTS.put("Genesis:34", 31);
        COUNTS.put("Genesis:35", 29);
        COUNTS.put("Genesis:36", 43);
        COUNTS.put("Genesis:37", 36);
        COUNTS.put("Genesis:38", 30);
        COUNTS.put("Genesis:39", 23);
        COUNTS.put("Genesis:40", 23);
        COUNTS.put("Genesis:41", 57);
        COUNTS.put("Genesis:42", 38);
        COUNTS.put("Genesis:43", 34);
        COUNTS.put("Genesis:44", 34);
        COUNTS.put("Genesis:45", 28);
        COUNTS.put("Genesis:46", 34);
        COUNTS.put("Genesis:47", 31);
        COUNTS.put("Genesis:48", 22);
        COUNTS.put("Genesis:49", 33);
        COUNTS.put("Genesis:50", 26);
        COUNTS.put("Exodus:1", 22);
        COUNTS.put("Exodus:2", 25);
        COUNTS.put("Exodus:3", 22);
        COUNTS.put("Exodus:4", 31);
        COUNTS.put("Exodus:5", 23);
        COUNTS.put("Exodus:6", 30);
        COUNTS.put("Exodus:7", 25);
        COUNTS.put("Exodus:8", 32);
        COUNTS.put("Exodus:9", 35);
        COUNTS.put("Exodus:10", 29);
        COUNTS.put("Exodus:11", 10);
        COUNTS.put("Exodus:12", 51);
        COUNTS.put("Exodus:13", 22);
        COUNTS.put("Exodus:14", 31);
        COUNTS.put("Exodus:15", 27);
        COUNTS.put("Exodus:16", 36);
        COUNTS.put("Exodus:17", 16);
        COUNTS.put("Exodus:18", 27);
        COUNTS.put("Exodus:19", 25);
        COUNTS.put("Exodus:20", 26);
        COUNTS.put("Exodus:21", 36);
        COUNTS.put("Exodus:22", 31);
        COUNTS.put("Exodus:23", 33);
        COUNTS.put("Exodus:24", 18);
        COUNTS.put("Exodus:25", 40);
        COUNTS.put("Exodus:26", 37);
        COUNTS.put("Exodus:27", 21);
        COUNTS.put("Exodus:28", 43);
        COUNTS.put("Exodus:29", 46);
        COUNTS.put("Exodus:30", 38);
        COUNTS.put("Exodus:31", 18);
        COUNTS.put("Exodus:32", 35);
        COUNTS.put("Exodus:33", 23);
        COUNTS.put("Exodus:34", 35);
        COUNTS.put("Exodus:35", 35);
        COUNTS.put("Exodus:36", 38);
        COUNTS.put("Exodus:37", 29);
        COUNTS.put("Exodus:38", 31);
        COUNTS.put("Exodus:39", 43);
        COUNTS.put("Exodus:40", 38);
        COUNTS.put("Leviticus:1", 17);
        COUNTS.put("Leviticus:2", 16);
        COUNTS.put("Leviticus:3", 17);
        COUNTS.put("Leviticus:4", 35);
        COUNTS.put("Leviticus:5", 19);
        COUNTS.put("Leviticus:6", 30);
        COUNTS.put("Leviticus:7", 38);
        COUNTS.put("Leviticus:8", 36);
        COUNTS.put("Leviticus:9", 24);
        COUNTS.put("Leviticus:10", 20);
        COUNTS.put("Leviticus:11", 47);
        COUNTS.put("Leviticus:12", 8);
        COUNTS.put("Leviticus:13", 59);
        COUNTS.put("Leviticus:14", 57);
        COUNTS.put("Leviticus:15", 33);
        COUNTS.put("Leviticus:16", 34);
        COUNTS.put("Leviticus:17", 16);
        COUNTS.put("Leviticus:18", 30);
        COUNTS.put("Leviticus:19", 37);
        COUNTS.put("Leviticus:20", 27);
        COUNTS.put("Leviticus:21", 24);
        COUNTS.put("Leviticus:22", 33);
        COUNTS.put("Leviticus:23", 44);
        COUNTS.put("Leviticus:24", 23);
        COUNTS.put("Leviticus:25", 55);
        COUNTS.put("Leviticus:26", 46);
        COUNTS.put("Leviticus:27", 34);
        COUNTS.put("Numbers:1", 54);
        COUNTS.put("Numbers:2", 34);
        COUNTS.put("Numbers:3", 51);
        COUNTS.put("Numbers:4", 49);
        COUNTS.put("Numbers:5", 31);
        COUNTS.put("Numbers:6", 27);
        COUNTS.put("Numbers:7", 89);
        COUNTS.put("Numbers:8", 26);
        COUNTS.put("Numbers:9", 23);
        COUNTS.put("Numbers:10", 36);
        COUNTS.put("Numbers:11", 35);
        COUNTS.put("Numbers:12", 16);
        COUNTS.put("Numbers:13", 33);
        COUNTS.put("Numbers:14", 45);
        COUNTS.put("Numbers:15", 41);
        COUNTS.put("Numbers:16", 50);
        COUNTS.put("Numbers:17", 13);
        COUNTS.put("Numbers:18", 32);
        COUNTS.put("Numbers:19", 22);
        COUNTS.put("Numbers:20", 29);
        COUNTS.put("Numbers:21", 35);
        COUNTS.put("Numbers:22", 41);
        COUNTS.put("Numbers:23", 30);
        COUNTS.put("Numbers:24", 25);
        COUNTS.put("Numbers:25", 18);
        COUNTS.put("Numbers:26", 65);
        COUNTS.put("Numbers:27", 23);
        COUNTS.put("Numbers:28", 31);
        COUNTS.put("Numbers:29", 39);
        COUNTS.put("Numbers:30", 16);
        COUNTS.put("Numbers:31", 54);
        COUNTS.put("Numbers:32", 42);
        COUNTS.put("Numbers:33", 56);
        COUNTS.put("Numbers:34", 29);
        COUNTS.put("Numbers:35", 34);
        COUNTS.put("Numbers:36", 13);
        COUNTS.put("Deuteronomy:1", 46);
        COUNTS.put("Deuteronomy:2", 37);
        COUNTS.put("Deuteronomy:3", 29);
        COUNTS.put("Deuteronomy:4", 49);
        COUNTS.put("Deuteronomy:5", 33);
        COUNTS.put("Deuteronomy:6", 25);
        COUNTS.put("Deuteronomy:7", 26);
        COUNTS.put("Deuteronomy:8", 20);
        COUNTS.put("Deuteronomy:9", 29);
        COUNTS.put("Deuteronomy:10", 22);
        COUNTS.put("Deuteronomy:11", 32);
        COUNTS.put("Deuteronomy:12", 32);
        COUNTS.put("Deuteronomy:13", 18);
        COUNTS.put("Deuteronomy:14", 29);
        COUNTS.put("Deuteronomy:15", 23);
        COUNTS.put("Deuteronomy:16", 22);
        COUNTS.put("Deuteronomy:17", 20);
        COUNTS.put("Deuteronomy:18", 22);
        COUNTS.put("Deuteronomy:19", 21);
        COUNTS.put("Deuteronomy:20", 20);
        COUNTS.put("Deuteronomy:21", 23);
        COUNTS.put("Deuteronomy:22", 30);
        COUNTS.put("Deuteronomy:23", 25);
        COUNTS.put("Deuteronomy:24", 22);
        COUNTS.put("Deuteronomy:25", 19);
        COUNTS.put("Deuteronomy:26", 19);
        COUNTS.put("Deuteronomy:27", 26);
        COUNTS.put("Deuteronomy:28", 68);
        COUNTS.put("Deuteronomy:29", 29);
        COUNTS.put("Deuteronomy:30", 20);
        COUNTS.put("Deuteronomy:31", 30);
        COUNTS.put("Deuteronomy:32", 52);
        COUNTS.put("Deuteronomy:33", 29);
        COUNTS.put("Deuteronomy:34", 12);
        COUNTS.put("Joshua:1", 18);
        COUNTS.put("Joshua:2", 24);
        COUNTS.put("Joshua:3", 17);
        COUNTS.put("Joshua:4", 24);
        COUNTS.put("Joshua:5", 15);
        COUNTS.put("Joshua:6", 27);
        COUNTS.put("Joshua:7", 26);
        COUNTS.put("Joshua:8", 35);
        COUNTS.put("Joshua:9", 27);
        COUNTS.put("Joshua:10", 43);
        COUNTS.put("Joshua:11", 23);
        COUNTS.put("Joshua:12", 24);
        COUNTS.put("Joshua:13", 33);
        COUNTS.put("Joshua:14", 15);
        COUNTS.put("Joshua:15", 63);
        COUNTS.put("Joshua:16", 10);
        COUNTS.put("Joshua:17", 18);
        COUNTS.put("Joshua:18", 28);
        COUNTS.put("Joshua:19", 51);
        COUNTS.put("Joshua:20", 9);
        COUNTS.put("Joshua:21", 45);
        COUNTS.put("Joshua:22", 34);
        COUNTS.put("Joshua:23", 16);
        COUNTS.put("Joshua:24", 33);
        COUNTS.put("Judges:1", 36);
        COUNTS.put("Judges:2", 23);
        COUNTS.put("Judges:3", 31);
        COUNTS.put("Judges:4", 24);
        COUNTS.put("Judges:5", 31);
        COUNTS.put("Judges:6", 40);
        COUNTS.put("Judges:7", 25);
        COUNTS.put("Judges:8", 35);
        COUNTS.put("Judges:9", 57);
        COUNTS.put("Judges:10", 18);
        COUNTS.put("Judges:11", 40);
        COUNTS.put("Judges:12", 15);
        COUNTS.put("Judges:13", 25);
        COUNTS.put("Judges:14", 20);
        COUNTS.put("Judges:15", 20);
        COUNTS.put("Judges:16", 31);
        COUNTS.put("Judges:17", 13);
        COUNTS.put("Judges:18", 31);
        COUNTS.put("Judges:19", 30);
        COUNTS.put("Judges:20", 48);
        COUNTS.put("Judges:21", 25);
        COUNTS.put("Ruth:1", 22);
        COUNTS.put("Ruth:2", 23);
        COUNTS.put("Ruth:3", 18);
        COUNTS.put("Ruth:4", 22);
        COUNTS.put("1 Samuel:1", 28);
        COUNTS.put("1 Samuel:2", 36);
        COUNTS.put("1 Samuel:3", 21);
        COUNTS.put("1 Samuel:4", 22);
        COUNTS.put("1 Samuel:5", 12);
        COUNTS.put("1 Samuel:6", 21);
        COUNTS.put("1 Samuel:7", 17);
        COUNTS.put("1 Samuel:8", 22);
        COUNTS.put("1 Samuel:9", 27);
        COUNTS.put("1 Samuel:10", 27);
        COUNTS.put("1 Samuel:11", 15);
        COUNTS.put("1 Samuel:12", 25);
        COUNTS.put("1 Samuel:13", 23);
        COUNTS.put("1 Samuel:14", 52);
        COUNTS.put("1 Samuel:15", 35);
        COUNTS.put("1 Samuel:16", 23);
        COUNTS.put("1 Samuel:17", 58);
        COUNTS.put("1 Samuel:18", 30);
        COUNTS.put("1 Samuel:19", 24);
        COUNTS.put("1 Samuel:20", 42);
        COUNTS.put("1 Samuel:21", 15);
        COUNTS.put("1 Samuel:22", 23);
        COUNTS.put("1 Samuel:23", 29);
        COUNTS.put("1 Samuel:24", 22);
        COUNTS.put("1 Samuel:25", 44);
        COUNTS.put("1 Samuel:26", 25);
        COUNTS.put("1 Samuel:27", 12);
        COUNTS.put("1 Samuel:28", 25);
        COUNTS.put("1 Samuel:29", 11);
        COUNTS.put("1 Samuel:30", 31);
        COUNTS.put("1 Samuel:31", 13);
        COUNTS.put("2 Samuel:1", 27);
        COUNTS.put("2 Samuel:2", 32);
        COUNTS.put("2 Samuel:3", 39);
        COUNTS.put("2 Samuel:4", 12);
        COUNTS.put("2 Samuel:5", 25);
        COUNTS.put("2 Samuel:6", 23);
        COUNTS.put("2 Samuel:7", 29);
        COUNTS.put("2 Samuel:8", 18);
        COUNTS.put("2 Samuel:9", 13);
        COUNTS.put("2 Samuel:10", 19);
        COUNTS.put("2 Samuel:11", 27);
        COUNTS.put("2 Samuel:12", 31);
        COUNTS.put("2 Samuel:13", 39);
        COUNTS.put("2 Samuel:14", 33);
        COUNTS.put("2 Samuel:15", 37);
        COUNTS.put("2 Samuel:16", 23);
        COUNTS.put("2 Samuel:17", 29);
        COUNTS.put("2 Samuel:18", 33);
        COUNTS.put("2 Samuel:19", 43);
        COUNTS.put("2 Samuel:20", 26);
        COUNTS.put("2 Samuel:21", 22);
        COUNTS.put("2 Samuel:22", 51);
        COUNTS.put("2 Samuel:23", 39);
        COUNTS.put("2 Samuel:24", 25);
        COUNTS.put("1 Kings:1", 53);
        COUNTS.put("1 Kings:2", 46);
        COUNTS.put("1 Kings:3", 28);
        COUNTS.put("1 Kings:4", 34);
        COUNTS.put("1 Kings:5", 18);
        COUNTS.put("1 Kings:6", 38);
        COUNTS.put("1 Kings:7", 51);
        COUNTS.put("1 Kings:8", 66);
        COUNTS.put("1 Kings:9", 28);
        COUNTS.put("1 Kings:10", 29);
        COUNTS.put("1 Kings:11", 43);
        COUNTS.put("1 Kings:12", 33);
        COUNTS.put("1 Kings:13", 34);
        COUNTS.put("1 Kings:14", 31);
        COUNTS.put("1 Kings:15", 34);
        COUNTS.put("1 Kings:16", 34);
        COUNTS.put("1 Kings:17", 24);
        COUNTS.put("1 Kings:18", 46);
        COUNTS.put("1 Kings:19", 21);
        COUNTS.put("1 Kings:20", 43);
        COUNTS.put("1 Kings:21", 29);
        COUNTS.put("1 Kings:22", 53);
        COUNTS.put("2 Kings:1", 18);
        COUNTS.put("2 Kings:2", 25);
        COUNTS.put("2 Kings:3", 27);
        COUNTS.put("2 Kings:4", 44);
        COUNTS.put("2 Kings:5", 27);
        COUNTS.put("2 Kings:6", 33);
        COUNTS.put("2 Kings:7", 20);
        COUNTS.put("2 Kings:8", 29);
        COUNTS.put("2 Kings:9", 37);
        COUNTS.put("2 Kings:10", 36);
        COUNTS.put("2 Kings:11", 21);
        COUNTS.put("2 Kings:12", 21);
        COUNTS.put("2 Kings:13", 25);
        COUNTS.put("2 Kings:14", 29);
        COUNTS.put("2 Kings:15", 38);
        COUNTS.put("2 Kings:16", 20);
        COUNTS.put("2 Kings:17", 41);
        COUNTS.put("2 Kings:18", 37);
        COUNTS.put("2 Kings:19", 37);
        COUNTS.put("2 Kings:20", 21);
        COUNTS.put("2 Kings:21", 26);
        COUNTS.put("2 Kings:22", 20);
        COUNTS.put("2 Kings:23", 37);
        COUNTS.put("2 Kings:24", 20);
        COUNTS.put("2 Kings:25", 30);
        COUNTS.put("1 Chronicles:1", 54);
        COUNTS.put("1 Chronicles:2", 55);
        COUNTS.put("1 Chronicles:3", 24);
        COUNTS.put("1 Chronicles:4", 43);
        COUNTS.put("1 Chronicles:5", 26);
        COUNTS.put("1 Chronicles:6", 81);
        COUNTS.put("1 Chronicles:7", 40);
        COUNTS.put("1 Chronicles:8", 40);
        COUNTS.put("1 Chronicles:9", 44);
        COUNTS.put("1 Chronicles:10", 14);
        COUNTS.put("1 Chronicles:11", 47);
        COUNTS.put("1 Chronicles:12", 40);
        COUNTS.put("1 Chronicles:13", 14);
        COUNTS.put("1 Chronicles:14", 17);
        COUNTS.put("1 Chronicles:15", 29);
        COUNTS.put("1 Chronicles:16", 43);
        COUNTS.put("1 Chronicles:17", 27);
        COUNTS.put("1 Chronicles:18", 17);
        COUNTS.put("1 Chronicles:19", 19);
        COUNTS.put("1 Chronicles:20", 8);
        COUNTS.put("1 Chronicles:21", 30);
        COUNTS.put("1 Chronicles:22", 19);
        COUNTS.put("1 Chronicles:23", 32);
        COUNTS.put("1 Chronicles:24", 31);
        COUNTS.put("1 Chronicles:25", 31);
        COUNTS.put("1 Chronicles:26", 32);
        COUNTS.put("1 Chronicles:27", 34);
        COUNTS.put("1 Chronicles:28", 21);
        COUNTS.put("1 Chronicles:29", 30);
        COUNTS.put("2 Chronicles:1", 17);
        COUNTS.put("2 Chronicles:2", 18);
        COUNTS.put("2 Chronicles:3", 17);
        COUNTS.put("2 Chronicles:4", 22);
        COUNTS.put("2 Chronicles:5", 14);
        COUNTS.put("2 Chronicles:6", 42);
        COUNTS.put("2 Chronicles:7", 22);
        COUNTS.put("2 Chronicles:8", 18);
        COUNTS.put("2 Chronicles:9", 31);
        COUNTS.put("2 Chronicles:10", 19);
        COUNTS.put("2 Chronicles:11", 23);
        COUNTS.put("2 Chronicles:12", 16);
        COUNTS.put("2 Chronicles:13", 22);
        COUNTS.put("2 Chronicles:14", 15);
        COUNTS.put("2 Chronicles:15", 19);
        COUNTS.put("2 Chronicles:16", 14);
        COUNTS.put("2 Chronicles:17", 19);
        COUNTS.put("2 Chronicles:18", 34);
        COUNTS.put("2 Chronicles:19", 11);
        COUNTS.put("2 Chronicles:20", 37);
        COUNTS.put("2 Chronicles:21", 20);
        COUNTS.put("2 Chronicles:22", 12);
        COUNTS.put("2 Chronicles:23", 21);
        COUNTS.put("2 Chronicles:24", 27);
        COUNTS.put("2 Chronicles:25", 28);
        COUNTS.put("2 Chronicles:26", 23);
        COUNTS.put("2 Chronicles:27", 9);
        COUNTS.put("2 Chronicles:28", 27);
        COUNTS.put("2 Chronicles:29", 36);
        COUNTS.put("2 Chronicles:30", 27);
        COUNTS.put("2 Chronicles:31", 21);
        COUNTS.put("2 Chronicles:32", 33);
        COUNTS.put("2 Chronicles:33", 25);
        COUNTS.put("2 Chronicles:34", 33);
        COUNTS.put("2 Chronicles:35", 27);
        COUNTS.put("2 Chronicles:36", 23);
        COUNTS.put("Ezra:1", 11);
        COUNTS.put("Ezra:2", 70);
        COUNTS.put("Ezra:3", 13);
        COUNTS.put("Ezra:4", 24);
        COUNTS.put("Ezra:5", 17);
        COUNTS.put("Ezra:6", 22);
        COUNTS.put("Ezra:7", 28);
        COUNTS.put("Ezra:8", 36);
        COUNTS.put("Ezra:9", 15);
        COUNTS.put("Ezra:10", 44);
        COUNTS.put("Nehemiah:1", 11);
        COUNTS.put("Nehemiah:2", 20);
        COUNTS.put("Nehemiah:3", 32);
        COUNTS.put("Nehemiah:4", 23);
        COUNTS.put("Nehemiah:5", 19);
        COUNTS.put("Nehemiah:6", 19);
        COUNTS.put("Nehemiah:7", 73);
        COUNTS.put("Nehemiah:8", 18);
        COUNTS.put("Nehemiah:9", 38);
        COUNTS.put("Nehemiah:10", 39);
        COUNTS.put("Nehemiah:11", 36);
        COUNTS.put("Nehemiah:12", 47);
        COUNTS.put("Nehemiah:13", 31);
        COUNTS.put("Esther:1", 22);
        COUNTS.put("Esther:2", 23);
        COUNTS.put("Esther:3", 15);
        COUNTS.put("Esther:4", 17);
        COUNTS.put("Esther:5", 14);
        COUNTS.put("Esther:6", 14);
        COUNTS.put("Esther:7", 10);
        COUNTS.put("Esther:8", 17);
        COUNTS.put("Esther:9", 32);
        COUNTS.put("Esther:10", 3);
        COUNTS.put("Job:1", 22);
        COUNTS.put("Job:2", 13);
        COUNTS.put("Job:3", 26);
        COUNTS.put("Job:4", 21);
        COUNTS.put("Job:5", 27);
        COUNTS.put("Job:6", 30);
        COUNTS.put("Job:7", 21);
        COUNTS.put("Job:8", 22);
        COUNTS.put("Job:9", 35);
        COUNTS.put("Job:10", 22);
        COUNTS.put("Job:11", 20);
        COUNTS.put("Job:12", 25);
        COUNTS.put("Job:13", 28);
        COUNTS.put("Job:14", 22);
        COUNTS.put("Job:15", 35);
        COUNTS.put("Job:16", 22);
        COUNTS.put("Job:17", 16);
        COUNTS.put("Job:18", 21);
        COUNTS.put("Job:19", 29);
        COUNTS.put("Job:20", 29);
        COUNTS.put("Job:21", 34);
        COUNTS.put("Job:22", 30);
        COUNTS.put("Job:23", 17);
        COUNTS.put("Job:24", 25);
        COUNTS.put("Job:25", 6);
        COUNTS.put("Job:26", 14);
        COUNTS.put("Job:27", 23);
        COUNTS.put("Job:28", 28);
        COUNTS.put("Job:29", 25);
        COUNTS.put("Job:30", 31);
        COUNTS.put("Job:31", 40);
        COUNTS.put("Job:32", 22);
        COUNTS.put("Job:33", 33);
        COUNTS.put("Job:34", 37);
        COUNTS.put("Job:35", 16);
        COUNTS.put("Job:36", 33);
        COUNTS.put("Job:37", 24);
        COUNTS.put("Job:38", 41);
        COUNTS.put("Job:39", 30);
        COUNTS.put("Job:40", 24);
        COUNTS.put("Job:41", 34);
        COUNTS.put("Job:42", 17);
        COUNTS.put("Psalms:1", 6);
        COUNTS.put("Psalms:2", 12);
        COUNTS.put("Psalms:3", 8);
        COUNTS.put("Psalms:4", 8);
        COUNTS.put("Psalms:5", 12);
        COUNTS.put("Psalms:6", 10);
        COUNTS.put("Psalms:7", 17);
        COUNTS.put("Psalms:8", 9);
        COUNTS.put("Psalms:9", 20);
        COUNTS.put("Psalms:10", 18);
        COUNTS.put("Psalms:11", 7);
        COUNTS.put("Psalms:12", 8);
        COUNTS.put("Psalms:13", 6);
        COUNTS.put("Psalms:14", 7);
        COUNTS.put("Psalms:15", 5);
        COUNTS.put("Psalms:16", 11);
        COUNTS.put("Psalms:17", 15);
        COUNTS.put("Psalms:18", 50);
        COUNTS.put("Psalms:19", 14);
        COUNTS.put("Psalms:20", 9);
        COUNTS.put("Psalms:21", 13);
        COUNTS.put("Psalms:22", 31);
        COUNTS.put("Psalms:23", 6);
        COUNTS.put("Psalms:24", 10);
        COUNTS.put("Psalms:25", 22);
        COUNTS.put("Psalms:26", 12);
        COUNTS.put("Psalms:27", 14);
        COUNTS.put("Psalms:28", 9);
        COUNTS.put("Psalms:29", 11);
        COUNTS.put("Psalms:30", 12);
        COUNTS.put("Psalms:31", 24);
        COUNTS.put("Psalms:32", 11);
        COUNTS.put("Psalms:33", 22);
        COUNTS.put("Psalms:34", 22);
        COUNTS.put("Psalms:35", 28);
        COUNTS.put("Psalms:36", 12);
        COUNTS.put("Psalms:37", 40);
        COUNTS.put("Psalms:38", 22);
        COUNTS.put("Psalms:39", 13);
        COUNTS.put("Psalms:40", 17);
        COUNTS.put("Psalms:41", 13);
        COUNTS.put("Psalms:42", 11);
        COUNTS.put("Psalms:43", 5);
        COUNTS.put("Psalms:44", 26);
        COUNTS.put("Psalms:45", 17);
        COUNTS.put("Psalms:46", 11);
        COUNTS.put("Psalms:47", 9);
        COUNTS.put("Psalms:48", 14);
        COUNTS.put("Psalms:49", 20);
        COUNTS.put("Psalms:50", 23);
        COUNTS.put("Psalms:51", 19);
        COUNTS.put("Psalms:52", 9);
        COUNTS.put("Psalms:53", 6);
        COUNTS.put("Psalms:54", 7);
        COUNTS.put("Psalms:55", 23);
        COUNTS.put("Psalms:56", 13);
        COUNTS.put("Psalms:57", 11);
        COUNTS.put("Psalms:58", 11);
        COUNTS.put("Psalms:59", 17);
        COUNTS.put("Psalms:60", 12);
        COUNTS.put("Psalms:61", 8);
        COUNTS.put("Psalms:62", 12);
        COUNTS.put("Psalms:63", 11);
        COUNTS.put("Psalms:64", 10);
        COUNTS.put("Psalms:65", 13);
        COUNTS.put("Psalms:66", 20);
        COUNTS.put("Psalms:67", 7);
        COUNTS.put("Psalms:68", 35);
        COUNTS.put("Psalms:69", 36);
        COUNTS.put("Psalms:70", 5);
        COUNTS.put("Psalms:71", 24);
        COUNTS.put("Psalms:72", 20);
        COUNTS.put("Psalms:73", 28);
        COUNTS.put("Psalms:74", 23);
        COUNTS.put("Psalms:75", 10);
        COUNTS.put("Psalms:76", 12);
        COUNTS.put("Psalms:77", 20);
        COUNTS.put("Psalms:78", 72);
        COUNTS.put("Psalms:79", 13);
        COUNTS.put("Psalms:80", 19);
        COUNTS.put("Psalms:81", 16);
        COUNTS.put("Psalms:82", 8);
        COUNTS.put("Psalms:83", 18);
        COUNTS.put("Psalms:84", 12);
        COUNTS.put("Psalms:85", 13);
        COUNTS.put("Psalms:86", 17);
        COUNTS.put("Psalms:87", 7);
        COUNTS.put("Psalms:88", 18);
        COUNTS.put("Psalms:89", 52);
        COUNTS.put("Psalms:90", 17);
        COUNTS.put("Psalms:91", 16);
        COUNTS.put("Psalms:92", 15);
        COUNTS.put("Psalms:93", 5);
        COUNTS.put("Psalms:94", 23);
        COUNTS.put("Psalms:95", 11);
        COUNTS.put("Psalms:96", 13);
        COUNTS.put("Psalms:97", 12);
        COUNTS.put("Psalms:98", 9);
        COUNTS.put("Psalms:99", 9);
        COUNTS.put("Psalms:100", 5);
        COUNTS.put("Psalms:101", 8);
        COUNTS.put("Psalms:102", 28);
        COUNTS.put("Psalms:103", 22);
        COUNTS.put("Psalms:104", 35);
        COUNTS.put("Psalms:105", 45);
        COUNTS.put("Psalms:106", 48);
        COUNTS.put("Psalms:107", 43);
        COUNTS.put("Psalms:108", 13);
        COUNTS.put("Psalms:109", 31);
        COUNTS.put("Psalms:110", 7);
        COUNTS.put("Psalms:111", 10);
        COUNTS.put("Psalms:112", 10);
        COUNTS.put("Psalms:113", 9);
        COUNTS.put("Psalms:114", 8);
        COUNTS.put("Psalms:115", 18);
        COUNTS.put("Psalms:116", 19);
        COUNTS.put("Psalms:117", 2);
        COUNTS.put("Psalms:118", 29);
        COUNTS.put("Psalms:119", 176);
        COUNTS.put("Psalms:120", 7);
        COUNTS.put("Psalms:121", 8);
        COUNTS.put("Psalms:122", 9);
        COUNTS.put("Psalms:123", 4);
        COUNTS.put("Psalms:124", 8);
        COUNTS.put("Psalms:125", 5);
        COUNTS.put("Psalms:126", 6);
        COUNTS.put("Psalms:127", 5);
        COUNTS.put("Psalms:128", 6);
        COUNTS.put("Psalms:129", 8);
        COUNTS.put("Psalms:130", 8);
        COUNTS.put("Psalms:131", 3);
        COUNTS.put("Psalms:132", 18);
        COUNTS.put("Psalms:133", 3);
        COUNTS.put("Psalms:134", 3);
        COUNTS.put("Psalms:135", 21);
        COUNTS.put("Psalms:136", 26);
        COUNTS.put("Psalms:137", 9);
        COUNTS.put("Psalms:138", 8);
        COUNTS.put("Psalms:139", 24);
        COUNTS.put("Psalms:140", 13);
        COUNTS.put("Psalms:141", 10);
        COUNTS.put("Psalms:142", 7);
        COUNTS.put("Psalms:143", 12);
        COUNTS.put("Psalms:144", 15);
        COUNTS.put("Psalms:145", 21);
        COUNTS.put("Psalms:146", 10);
        COUNTS.put("Psalms:147", 20);
        COUNTS.put("Psalms:148", 14);
        COUNTS.put("Psalms:149", 9);
        COUNTS.put("Psalms:150", 6);
        COUNTS.put("Proverbs:1", 33);
        COUNTS.put("Proverbs:2", 22);
        COUNTS.put("Proverbs:3", 35);
        COUNTS.put("Proverbs:4", 27);
        COUNTS.put("Proverbs:5", 23);
        COUNTS.put("Proverbs:6", 35);
        COUNTS.put("Proverbs:7", 27);
        COUNTS.put("Proverbs:8", 36);
        COUNTS.put("Proverbs:9", 18);
        COUNTS.put("Proverbs:10", 32);
        COUNTS.put("Proverbs:11", 31);
        COUNTS.put("Proverbs:12", 28);
        COUNTS.put("Proverbs:13", 25);
        COUNTS.put("Proverbs:14", 35);
        COUNTS.put("Proverbs:15", 33);
        COUNTS.put("Proverbs:16", 33);
        COUNTS.put("Proverbs:17", 28);
        COUNTS.put("Proverbs:18", 24);
        COUNTS.put("Proverbs:19", 29);
        COUNTS.put("Proverbs:20", 30);
        COUNTS.put("Proverbs:21", 31);
        COUNTS.put("Proverbs:22", 29);
        COUNTS.put("Proverbs:23", 35);
        COUNTS.put("Proverbs:24", 34);
        COUNTS.put("Proverbs:25", 28);
        COUNTS.put("Proverbs:26", 28);
        COUNTS.put("Proverbs:27", 27);
        COUNTS.put("Proverbs:28", 28);
        COUNTS.put("Proverbs:29", 27);
        COUNTS.put("Proverbs:30", 33);
        COUNTS.put("Proverbs:31", 31);
        COUNTS.put("Ecclesiastes:1", 18);
        COUNTS.put("Ecclesiastes:2", 26);
        COUNTS.put("Ecclesiastes:3", 22);
        COUNTS.put("Ecclesiastes:4", 16);
        COUNTS.put("Ecclesiastes:5", 20);
        COUNTS.put("Ecclesiastes:6", 12);
        COUNTS.put("Ecclesiastes:7", 29);
        COUNTS.put("Ecclesiastes:8", 17);
        COUNTS.put("Ecclesiastes:9", 18);
        COUNTS.put("Ecclesiastes:10", 20);
        COUNTS.put("Ecclesiastes:11", 10);
        COUNTS.put("Ecclesiastes:12", 14);
        COUNTS.put("Song of Solomon:1", 17);
        COUNTS.put("Song of Solomon:2", 17);
        COUNTS.put("Song of Solomon:3", 11);
        COUNTS.put("Song of Solomon:4", 16);
        COUNTS.put("Song of Solomon:5", 16);
        COUNTS.put("Song of Solomon:6", 13);
        COUNTS.put("Song of Solomon:7", 13);
        COUNTS.put("Song of Solomon:8", 14);
        COUNTS.put("Isaiah:1", 31);
        COUNTS.put("Isaiah:2", 22);
        COUNTS.put("Isaiah:3", 26);
        COUNTS.put("Isaiah:4", 6);
        COUNTS.put("Isaiah:5", 30);
        COUNTS.put("Isaiah:6", 13);
        COUNTS.put("Isaiah:7", 25);
        COUNTS.put("Isaiah:8", 22);
        COUNTS.put("Isaiah:9", 21);
        COUNTS.put("Isaiah:10", 34);
        COUNTS.put("Isaiah:11", 16);
        COUNTS.put("Isaiah:12", 6);
        COUNTS.put("Isaiah:13", 22);
        COUNTS.put("Isaiah:14", 32);
        COUNTS.put("Isaiah:15", 9);
        COUNTS.put("Isaiah:16", 14);
        COUNTS.put("Isaiah:17", 14);
        COUNTS.put("Isaiah:18", 7);
        COUNTS.put("Isaiah:19", 25);
        COUNTS.put("Isaiah:20", 6);
        COUNTS.put("Isaiah:21", 17);
        COUNTS.put("Isaiah:22", 25);
        COUNTS.put("Isaiah:23", 18);
        COUNTS.put("Isaiah:24", 23);
        COUNTS.put("Isaiah:25", 12);
        COUNTS.put("Isaiah:26", 21);
        COUNTS.put("Isaiah:27", 13);
        COUNTS.put("Isaiah:28", 29);
        COUNTS.put("Isaiah:29", 24);
        COUNTS.put("Isaiah:30", 33);
        COUNTS.put("Isaiah:31", 9);
        COUNTS.put("Isaiah:32", 20);
        COUNTS.put("Isaiah:33", 24);
        COUNTS.put("Isaiah:34", 17);
        COUNTS.put("Isaiah:35", 10);
        COUNTS.put("Isaiah:36", 22);
        COUNTS.put("Isaiah:37", 38);
        COUNTS.put("Isaiah:38", 22);
        COUNTS.put("Isaiah:39", 8);
        COUNTS.put("Isaiah:40", 31);
        COUNTS.put("Isaiah:41", 29);
        COUNTS.put("Isaiah:42", 25);
        COUNTS.put("Isaiah:43", 28);
        COUNTS.put("Isaiah:44", 28);
        COUNTS.put("Isaiah:45", 25);
        COUNTS.put("Isaiah:46", 13);
        COUNTS.put("Isaiah:47", 15);
        COUNTS.put("Isaiah:48", 22);
        COUNTS.put("Isaiah:49", 26);
        COUNTS.put("Isaiah:50", 11);
        COUNTS.put("Isaiah:51", 23);
        COUNTS.put("Isaiah:52", 15);
        COUNTS.put("Isaiah:53", 12);
        COUNTS.put("Isaiah:54", 17);
        COUNTS.put("Isaiah:55", 13);
        COUNTS.put("Isaiah:56", 12);
        COUNTS.put("Isaiah:57", 21);
        COUNTS.put("Isaiah:58", 14);
        COUNTS.put("Isaiah:59", 21);
        COUNTS.put("Isaiah:60", 22);
        COUNTS.put("Isaiah:61", 11);
        COUNTS.put("Isaiah:62", 12);
        COUNTS.put("Isaiah:63", 19);
        COUNTS.put("Isaiah:64", 12);
        COUNTS.put("Isaiah:65", 25);
        COUNTS.put("Isaiah:66", 24);
        COUNTS.put("Jeremiah:1", 19);
        COUNTS.put("Jeremiah:2", 37);
        COUNTS.put("Jeremiah:3", 25);
        COUNTS.put("Jeremiah:4", 31);
        COUNTS.put("Jeremiah:5", 31);
        COUNTS.put("Jeremiah:6", 30);
        COUNTS.put("Jeremiah:7", 34);
        COUNTS.put("Jeremiah:8", 22);
        COUNTS.put("Jeremiah:9", 26);
        COUNTS.put("Jeremiah:10", 25);
        COUNTS.put("Jeremiah:11", 23);
        COUNTS.put("Jeremiah:12", 17);
        COUNTS.put("Jeremiah:13", 27);
        COUNTS.put("Jeremiah:14", 22);
        COUNTS.put("Jeremiah:15", 21);
        COUNTS.put("Jeremiah:16", 21);
        COUNTS.put("Jeremiah:17", 27);
        COUNTS.put("Jeremiah:18", 23);
        COUNTS.put("Jeremiah:19", 15);
        COUNTS.put("Jeremiah:20", 18);
        COUNTS.put("Jeremiah:21", 10);
        COUNTS.put("Jeremiah:22", 30);
        COUNTS.put("Jeremiah:23", 40);
        COUNTS.put("Jeremiah:24", 10);
        COUNTS.put("Jeremiah:25", 38);
        COUNTS.put("Jeremiah:26", 24);
        COUNTS.put("Jeremiah:27", 22);
        COUNTS.put("Jeremiah:28", 17);
        COUNTS.put("Jeremiah:29", 32);
        COUNTS.put("Jeremiah:30", 24);
        COUNTS.put("Jeremiah:31", 40);
        COUNTS.put("Jeremiah:32", 44);
        COUNTS.put("Jeremiah:33", 26);
        COUNTS.put("Jeremiah:34", 22);
        COUNTS.put("Jeremiah:35", 19);
        COUNTS.put("Jeremiah:36", 32);
        COUNTS.put("Jeremiah:37", 21);
        COUNTS.put("Jeremiah:38", 28);
        COUNTS.put("Jeremiah:39", 18);
        COUNTS.put("Jeremiah:40", 16);
        COUNTS.put("Jeremiah:41", 18);
        COUNTS.put("Jeremiah:42", 22);
        COUNTS.put("Jeremiah:43", 13);
        COUNTS.put("Jeremiah:44", 30);
        COUNTS.put("Jeremiah:45", 5);
        COUNTS.put("Jeremiah:46", 28);
        COUNTS.put("Jeremiah:47", 7);
        COUNTS.put("Jeremiah:48", 47);
        COUNTS.put("Jeremiah:49", 39);
        COUNTS.put("Jeremiah:50", 46);
        COUNTS.put("Jeremiah:51", 64);
        COUNTS.put("Jeremiah:52", 34);
        COUNTS.put("Lamentations:1", 22);
        COUNTS.put("Lamentations:2", 22);
        COUNTS.put("Lamentations:3", 66);
        COUNTS.put("Lamentations:4", 22);
        COUNTS.put("Lamentations:5", 22);
        COUNTS.put("Ezekiel:1", 28);
        COUNTS.put("Ezekiel:2", 10);
        COUNTS.put("Ezekiel:3", 27);
        COUNTS.put("Ezekiel:4", 17);
        COUNTS.put("Ezekiel:5", 17);
        COUNTS.put("Ezekiel:6", 14);
        COUNTS.put("Ezekiel:7", 27);
        COUNTS.put("Ezekiel:8", 18);
        COUNTS.put("Ezekiel:9", 11);
        COUNTS.put("Ezekiel:10", 22);
        COUNTS.put("Ezekiel:11", 25);
        COUNTS.put("Ezekiel:12", 28);
        COUNTS.put("Ezekiel:13", 23);
        COUNTS.put("Ezekiel:14", 23);
        COUNTS.put("Ezekiel:15", 8);
        COUNTS.put("Ezekiel:16", 63);
        COUNTS.put("Ezekiel:17", 24);
        COUNTS.put("Ezekiel:18", 32);
        COUNTS.put("Ezekiel:19", 14);
        COUNTS.put("Ezekiel:20", 49);
        COUNTS.put("Ezekiel:21", 35);
        COUNTS.put("Ezekiel:22", 31);
        COUNTS.put("Ezekiel:23", 49);
        COUNTS.put("Ezekiel:24", 27);
        COUNTS.put("Ezekiel:25", 17);
        COUNTS.put("Ezekiel:26", 21);
        COUNTS.put("Ezekiel:27", 36);
        COUNTS.put("Ezekiel:28", 26);
        COUNTS.put("Ezekiel:29", 21);
        COUNTS.put("Ezekiel:30", 26);
        COUNTS.put("Ezekiel:31", 18);
        COUNTS.put("Ezekiel:32", 32);
        COUNTS.put("Ezekiel:33", 33);
        COUNTS.put("Ezekiel:34", 31);
        COUNTS.put("Ezekiel:35", 15);
        COUNTS.put("Ezekiel:36", 38);
        COUNTS.put("Ezekiel:37", 28);
        COUNTS.put("Ezekiel:38", 23);
        COUNTS.put("Ezekiel:39", 29);
        COUNTS.put("Ezekiel:40", 54);
        COUNTS.put("Ezekiel:41", 26);
        COUNTS.put("Ezekiel:42", 20);
        COUNTS.put("Ezekiel:43", 27);
        COUNTS.put("Ezekiel:44", 31);
        COUNTS.put("Ezekiel:45", 25);
        COUNTS.put("Ezekiel:46", 24);
        COUNTS.put("Ezekiel:47", 23);
        COUNTS.put("Ezekiel:48", 35);
        COUNTS.put("Daniel:1", 21);
        COUNTS.put("Daniel:2", 49);
        COUNTS.put("Daniel:3", 30);
        COUNTS.put("Daniel:4", 37);
        COUNTS.put("Daniel:5", 31);
        COUNTS.put("Daniel:6", 28);
        COUNTS.put("Daniel:7", 28);
        COUNTS.put("Daniel:8", 27);
        COUNTS.put("Daniel:9", 27);
        COUNTS.put("Daniel:10", 21);
        COUNTS.put("Daniel:11", 45);
        COUNTS.put("Daniel:12", 13);
        COUNTS.put("Hosea:1", 11);
        COUNTS.put("Hosea:2", 23);
        COUNTS.put("Hosea:3", 5);
        COUNTS.put("Hosea:4", 19);
        COUNTS.put("Hosea:5", 15);
        COUNTS.put("Hosea:6", 11);
        COUNTS.put("Hosea:7", 16);
        COUNTS.put("Hosea:8", 14);
        COUNTS.put("Hosea:9", 17);
        COUNTS.put("Hosea:10", 15);
        COUNTS.put("Hosea:11", 12);
        COUNTS.put("Hosea:12", 14);
        COUNTS.put("Hosea:13", 16);
        COUNTS.put("Hosea:14", 9);
        COUNTS.put("Joel:1", 20);
        COUNTS.put("Joel:2", 32);
        COUNTS.put("Joel:3", 21);
        COUNTS.put("Amos:1", 15);
        COUNTS.put("Amos:2", 16);
        COUNTS.put("Amos:3", 15);
        COUNTS.put("Amos:4", 13);
        COUNTS.put("Amos:5", 27);
        COUNTS.put("Amos:6", 14);
        COUNTS.put("Amos:7", 17);
        COUNTS.put("Amos:8", 14);
        COUNTS.put("Amos:9", 15);
        COUNTS.put("Obadiah:1", 21);
        COUNTS.put("Jonah:1", 17);
        COUNTS.put("Jonah:2", 10);
        COUNTS.put("Jonah:3", 10);
        COUNTS.put("Jonah:4", 11);
        COUNTS.put("Micah:1", 16);
        COUNTS.put("Micah:2", 13);
        COUNTS.put("Micah:3", 12);
        COUNTS.put("Micah:4", 13);
        COUNTS.put("Micah:5", 15);
        COUNTS.put("Micah:6", 16);
        COUNTS.put("Micah:7", 20);
        COUNTS.put("Nahum:1", 15);
        COUNTS.put("Nahum:2", 13);
        COUNTS.put("Nahum:3", 19);
        COUNTS.put("Habakkuk:1", 17);
        COUNTS.put("Habakkuk:2", 20);
        COUNTS.put("Habakkuk:3", 19);
        COUNTS.put("Zephaniah:1", 18);
        COUNTS.put("Zephaniah:2", 15);
        COUNTS.put("Zephaniah:3", 20);
        COUNTS.put("Haggai:1", 15);
        COUNTS.put("Haggai:2", 23);
        COUNTS.put("Zechariah:1", 21);
        COUNTS.put("Zechariah:2", 13);
        COUNTS.put("Zechariah:3", 10);
        COUNTS.put("Zechariah:4", 14);
        COUNTS.put("Zechariah:5", 11);
        COUNTS.put("Zechariah:6", 15);
        COUNTS.put("Zechariah:7", 14);
        COUNTS.put("Zechariah:8", 23);
        COUNTS.put("Zechariah:9", 17);
        COUNTS.put("Zechariah:10", 12);
        COUNTS.put("Zechariah:11", 17);
        COUNTS.put("Zechariah:12", 14);
        COUNTS.put("Zechariah:13", 9);
        COUNTS.put("Zechariah:14", 21);
        COUNTS.put("Malachi:1", 14);
        COUNTS.put("Malachi:2", 17);
        COUNTS.put("Malachi:3", 18);
        COUNTS.put("Malachi:4", 6);
        COUNTS.put("Matthew:1", 25);
        COUNTS.put("Matthew:2", 23);
        COUNTS.put("Matthew:3", 17);
        COUNTS.put("Matthew:4", 25);
        COUNTS.put("Matthew:5", 48);
        COUNTS.put("Matthew:6", 34);
        COUNTS.put("Matthew:7", 29);
        COUNTS.put("Matthew:8", 34);
        COUNTS.put("Matthew:9", 38);
        COUNTS.put("Matthew:10", 42);
        COUNTS.put("Matthew:11", 30);
        COUNTS.put("Matthew:12", 50);
        COUNTS.put("Matthew:13", 58);
        COUNTS.put("Matthew:14", 36);
        COUNTS.put("Matthew:15", 39);
        COUNTS.put("Matthew:16", 28);
        COUNTS.put("Matthew:17", 27);
        COUNTS.put("Matthew:18", 35);
        COUNTS.put("Matthew:19", 30);
        COUNTS.put("Matthew:20", 34);
        COUNTS.put("Matthew:21", 46);
        COUNTS.put("Matthew:22", 46);
        COUNTS.put("Matthew:23", 39);
        COUNTS.put("Matthew:24", 51);
        COUNTS.put("Matthew:25", 46);
        COUNTS.put("Matthew:26", 75);
        COUNTS.put("Matthew:27", 66);
        COUNTS.put("Matthew:28", 20);
        COUNTS.put("Mark:1", 45);
        COUNTS.put("Mark:2", 28);
        COUNTS.put("Mark:3", 35);
        COUNTS.put("Mark:4", 41);
        COUNTS.put("Mark:5", 43);
        COUNTS.put("Mark:6", 56);
        COUNTS.put("Mark:7", 37);
        COUNTS.put("Mark:8", 38);
        COUNTS.put("Mark:9", 50);
        COUNTS.put("Mark:10", 52);
        COUNTS.put("Mark:11", 33);
        COUNTS.put("Mark:12", 44);
        COUNTS.put("Mark:13", 37);
        COUNTS.put("Mark:14", 72);
        COUNTS.put("Mark:15", 47);
        COUNTS.put("Mark:16", 20);
        COUNTS.put("Luke:1", 80);
        COUNTS.put("Luke:2", 52);
        COUNTS.put("Luke:3", 38);
        COUNTS.put("Luke:4", 44);
        COUNTS.put("Luke:5", 39);
        COUNTS.put("Luke:6", 49);
        COUNTS.put("Luke:7", 50);
        COUNTS.put("Luke:8", 56);
        COUNTS.put("Luke:9", 62);
        COUNTS.put("Luke:10", 42);
        COUNTS.put("Luke:11", 54);
        COUNTS.put("Luke:12", 59);
        COUNTS.put("Luke:13", 35);
        COUNTS.put("Luke:14", 35);
        COUNTS.put("Luke:15", 32);
        COUNTS.put("Luke:16", 31);
        COUNTS.put("Luke:17", 37);
        COUNTS.put("Luke:18", 43);
        COUNTS.put("Luke:19", 48);
        COUNTS.put("Luke:20", 47);
        COUNTS.put("Luke:21", 38);
        COUNTS.put("Luke:22", 71);
        COUNTS.put("Luke:23", 56);
        COUNTS.put("Luke:24", 53);
        COUNTS.put("John:1", 51);
        COUNTS.put("John:2", 25);
        COUNTS.put("John:3", 36);
        COUNTS.put("John:4", 54);
        COUNTS.put("John:5", 47);
        COUNTS.put("John:6", 71);
        COUNTS.put("John:7", 53);
        COUNTS.put("John:8", 59);
        COUNTS.put("John:9", 41);
        COUNTS.put("John:10", 42);
        COUNTS.put("John:11", 57);
        COUNTS.put("John:12", 50);
        COUNTS.put("John:13", 38);
        COUNTS.put("John:14", 31);
        COUNTS.put("John:15", 27);
        COUNTS.put("John:16", 33);
        COUNTS.put("John:17", 26);
        COUNTS.put("John:18", 40);
        COUNTS.put("John:19", 42);
        COUNTS.put("John:20", 31);
        COUNTS.put("John:21", 25);
        COUNTS.put("Acts:1", 26);
        COUNTS.put("Acts:2", 47);
        COUNTS.put("Acts:3", 26);
        COUNTS.put("Acts:4", 37);
        COUNTS.put("Acts:5", 42);
        COUNTS.put("Acts:6", 15);
        COUNTS.put("Acts:7", 60);
        COUNTS.put("Acts:8", 40);
        COUNTS.put("Acts:9", 43);
        COUNTS.put("Acts:10", 48);
        COUNTS.put("Acts:11", 30);
        COUNTS.put("Acts:12", 25);
        COUNTS.put("Acts:13", 52);
        COUNTS.put("Acts:14", 28);
        COUNTS.put("Acts:15", 41);
        COUNTS.put("Acts:16", 40);
        COUNTS.put("Acts:17", 34);
        COUNTS.put("Acts:18", 28);
        COUNTS.put("Acts:19", 41);
        COUNTS.put("Acts:20", 38);
        COUNTS.put("Acts:21", 40);
        COUNTS.put("Acts:22", 30);
        COUNTS.put("Acts:23", 35);
        COUNTS.put("Acts:24", 27);
        COUNTS.put("Acts:25", 27);
        COUNTS.put("Acts:26", 32);
        COUNTS.put("Acts:27", 44);
        COUNTS.put("Acts:28", 31);
        COUNTS.put("Romans:1", 32);
        COUNTS.put("Romans:2", 29);
        COUNTS.put("Romans:3", 31);
        COUNTS.put("Romans:4", 25);
        COUNTS.put("Romans:5", 21);
        COUNTS.put("Romans:6", 23);
        COUNTS.put("Romans:7", 25);
        COUNTS.put("Romans:8", 39);
        COUNTS.put("Romans:9", 33);
        COUNTS.put("Romans:10", 21);
        COUNTS.put("Romans:11", 36);
        COUNTS.put("Romans:12", 21);
        COUNTS.put("Romans:13", 14);
        COUNTS.put("Romans:14", 23);
        COUNTS.put("Romans:15", 33);
        COUNTS.put("Romans:16", 27);
        COUNTS.put("1 Corinthians:1", 31);
        COUNTS.put("1 Corinthians:2", 16);
        COUNTS.put("1 Corinthians:3", 23);
        COUNTS.put("1 Corinthians:4", 21);
        COUNTS.put("1 Corinthians:5", 13);
        COUNTS.put("1 Corinthians:6", 20);
        COUNTS.put("1 Corinthians:7", 40);
        COUNTS.put("1 Corinthians:8", 13);
        COUNTS.put("1 Corinthians:9", 27);
        COUNTS.put("1 Corinthians:10", 33);
        COUNTS.put("1 Corinthians:11", 34);
        COUNTS.put("1 Corinthians:12", 31);
        COUNTS.put("1 Corinthians:13", 13);
        COUNTS.put("1 Corinthians:14", 40);
        COUNTS.put("1 Corinthians:15", 58);
        COUNTS.put("1 Corinthians:16", 24);
        COUNTS.put("2 Corinthians:1", 24);
        COUNTS.put("2 Corinthians:2", 17);
        COUNTS.put("2 Corinthians:3", 18);
        COUNTS.put("2 Corinthians:4", 18);
        COUNTS.put("2 Corinthians:5", 21);
        COUNTS.put("2 Corinthians:6", 18);
        COUNTS.put("2 Corinthians:7", 16);
        COUNTS.put("2 Corinthians:8", 24);
        COUNTS.put("2 Corinthians:9", 15);
        COUNTS.put("2 Corinthians:10", 18);
        COUNTS.put("2 Corinthians:11", 33);
        COUNTS.put("2 Corinthians:12", 21);
        COUNTS.put("2 Corinthians:13", 14);
        COUNTS.put("Galatians:1", 24);
        COUNTS.put("Galatians:2", 21);
        COUNTS.put("Galatians:3", 29);
        COUNTS.put("Galatians:4", 31);
        COUNTS.put("Galatians:5", 26);
        COUNTS.put("Galatians:6", 18);
        COUNTS.put("Ephesians:1", 23);
        COUNTS.put("Ephesians:2", 22);
        COUNTS.put("Ephesians:3", 21);
        COUNTS.put("Ephesians:4", 32);
        COUNTS.put("Ephesians:5", 33);
        COUNTS.put("Ephesians:6", 24);
        COUNTS.put("Philippians:1", 30);
        COUNTS.put("Philippians:2", 30);
        COUNTS.put("Philippians:3", 21);
        COUNTS.put("Philippians:4", 23);
        COUNTS.put("Colossians:1", 29);
        COUNTS.put("Colossians:2", 23);
        COUNTS.put("Colossians:3", 25);
        COUNTS.put("Colossians:4", 18);
        COUNTS.put("1 Thessalonians:1", 10);
        COUNTS.put("1 Thessalonians:2", 20);
        COUNTS.put("1 Thessalonians:3", 13);
        COUNTS.put("1 Thessalonians:4", 18);
        COUNTS.put("1 Thessalonians:5", 28);
        COUNTS.put("2 Thessalonians:1", 12);
        COUNTS.put("2 Thessalonians:2", 17);
        COUNTS.put("2 Thessalonians:3", 18);
        COUNTS.put("1 Timothy:1", 20);
        COUNTS.put("1 Timothy:2", 15);
        COUNTS.put("1 Timothy:3", 16);
        COUNTS.put("1 Timothy:4", 16);
        COUNTS.put("1 Timothy:5", 25);
        COUNTS.put("1 Timothy:6", 21);
        COUNTS.put("2 Timothy:1", 18);
        COUNTS.put("2 Timothy:2", 26);
        COUNTS.put("2 Timothy:3", 17);
        COUNTS.put("2 Timothy:4", 22);
        COUNTS.put("Titus:1", 16);
        COUNTS.put("Titus:2", 15);
        COUNTS.put("Titus:3", 15);
        COUNTS.put("Philemon:1", 25);
        COUNTS.put("Hebrews:1", 14);
        COUNTS.put("Hebrews:2", 18);
        COUNTS.put("Hebrews:3", 19);
        COUNTS.put("Hebrews:4", 16);
        COUNTS.put("Hebrews:5", 14);
        COUNTS.put("Hebrews:6", 20);
        COUNTS.put("Hebrews:7", 28);
        COUNTS.put("Hebrews:8", 13);
        COUNTS.put("Hebrews:9", 28);
        COUNTS.put("Hebrews:10", 39);
        COUNTS.put("Hebrews:11", 40);
        COUNTS.put("Hebrews:12", 29);
        COUNTS.put("Hebrews:13", 25);
        COUNTS.put("James:1", 27);
        COUNTS.put("James:2", 26);
        COUNTS.put("James:3", 18);
        COUNTS.put("James:4", 17);
        COUNTS.put("James:5", 20);
        COUNTS.put("1 Peter:1", 25);
        COUNTS.put("1 Peter:2", 25);
        COUNTS.put("1 Peter:3", 22);
        COUNTS.put("1 Peter:4", 19);
        COUNTS.put("1 Peter:5", 14);
        COUNTS.put("2 Peter:1", 21);
        COUNTS.put("2 Peter:2", 22);
        COUNTS.put("2 Peter:3", 18);
        COUNTS.put("1 John:1", 10);
        COUNTS.put("1 John:2", 29);
        COUNTS.put("1 John:3", 24);
        COUNTS.put("1 John:4", 21);
        COUNTS.put("1 John:5", 21);
        COUNTS.put("2 John:1", 13);
        COUNTS.put("3 John:1", 15);
        COUNTS.put("Jude:1", 25);
        COUNTS.put("Revelation:1", 20);
        COUNTS.put("Revelation:2", 29);
        COUNTS.put("Revelation:3", 22);
        COUNTS.put("Revelation:4", 11);
        COUNTS.put("Revelation:5", 14);
        COUNTS.put("Revelation:6", 17);
        COUNTS.put("Revelation:7", 17);
        COUNTS.put("Revelation:8", 13);
        COUNTS.put("Revelation:9", 21);
        COUNTS.put("Revelation:10", 11);
        COUNTS.put("Revelation:11", 19);
        COUNTS.put("Revelation:12", 17);
        COUNTS.put("Revelation:13", 18);
        COUNTS.put("Revelation:14", 20);
        COUNTS.put("Revelation:15", 8);
        COUNTS.put("Revelation:16", 21);
        COUNTS.put("Revelation:17", 18);
        COUNTS.put("Revelation:18", 24);
        COUNTS.put("Revelation:19", 21);
        COUNTS.put("Revelation:20", 15);
        COUNTS.put("Revelation:21", 27);
        COUNTS.put("Revelation:22", 21);
    }

    public static int getVerseCount(String book, int chapter) {
        Integer c = COUNTS.get(book + ":" + chapter);
        return c != null ? c : 30;
    }
}